-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_memory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  conversation_id character varying,
  message_type character varying,
  role character varying,
  content text,
  tokens_used integer DEFAULT 0,
  embedding USER-DEFINED,
  metadata jsonb,
  importance_score integer DEFAULT 0,
  extracted_entities jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ai_memory_pkey PRIMARY KEY (id),
  CONSTRAINT ai_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  asset_type character varying NOT NULL,
  source_type character varying,
  name character varying NOT NULL,
  description text,
  file_url character varying,
  content text,
  metadata jsonb,
  tags ARRAY,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.campaign_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  user_id uuid NOT NULL,
  task_id character varying NOT NULL,
  status character varying DEFAULT 'PENDING'::character varying,
  lead_count integer DEFAULT 0,
  result jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campaign_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_tasks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.campaign_templates (
  campaign_id uuid NOT NULL,
  template_id uuid NOT NULL,
  CONSTRAINT campaign_templates_pkey PRIMARY KEY (campaign_id, template_id),
  CONSTRAINT campaign_templates_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_templates_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  status character varying DEFAULT 'draft'::character varying,
  total_leads integer DEFAULT 0,
  sent_count integer DEFAULT 0,
  opened_count integer DEFAULT 0,
  clicked_count integer DEFAULT 0,
  replied_count integer DEFAULT 0,
  bounced_count integer DEFAULT 0,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  template_id uuid,
  variable_mapping jsonb,
  last_processed_index integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_credentials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  email_address character varying NOT NULL,
  encrypted_password text NOT NULL,
  app_password character varying,
  provider character varying DEFAULT 'gmail'::character varying,
  is_verified boolean DEFAULT false,
  verification_method character varying,
  verified_at timestamp with time zone,
  last_tested_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT email_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  leads_file_id uuid NOT NULL,
  lead_email character varying NOT NULL,
  email_credential_id uuid,
  status character varying DEFAULT 'pending'::character varying,
  message_id character varying,
  subject_line character varying,
  html_content text,
  text_content text,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  last_error text,
  error_code character varying,
  sent_at timestamp with time zone,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  replied_at timestamp with time zone,
  bounced_at timestamp with time zone,
  bounce_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_logs_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT email_logs_leads_file_id_fkey FOREIGN KEY (leads_file_id) REFERENCES public.leads(id),
  CONSTRAINT email_logs_email_credential_id_fkey FOREIGN KEY (email_credential_id) REFERENCES public.email_credentials(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  campaign_id uuid,
  file_name character varying NOT NULL,
  content jsonb NOT NULL,
  columns jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT leads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.otp_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  email character varying NOT NULL,
  code character varying NOT NULL,
  purpose character varying DEFAULT 'signup'::character varying,
  is_used boolean DEFAULT false,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT otp_codes_pkey PRIMARY KEY (id),
  CONSTRAINT otp_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  html_content text,
  text_content text,
  subject_line character varying,
  is_default boolean DEFAULT false,
  is_ai_generated boolean DEFAULT false,
  tags ARRAY,
  variables jsonb,
  preview_url character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT templates_pkey PRIMARY KEY (id),
  CONSTRAINT templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_resumes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  file_name character varying,
  file_url character varying,
  raw_text text,
  skills jsonb,
  projects jsonb,
  experience jsonb,
  education jsonb,
  social_media_links jsonb,
  certifications jsonb,
  objective text,
  parsed_metadata jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_resumes_pkey PRIMARY KEY (id),
  CONSTRAINT user_resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  theme character varying DEFAULT 'light'::character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  language character varying DEFAULT 'en'::character varying,
  notifications_enabled boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  full_name character varying,
  phone character varying,
  resume_uploaded boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  role character varying,
  encrypted_app_password text,
  app_password_verified boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);